version: '3.7'

services:
    microservice:
        build:
            context: ./microservice
        image: tinkoff-microservice
        container_name: tinkoff-microservice
        restart: unless-stopped
        ports:
            - "8000:8000"
        command: gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker tinkoff-microservice:api

    # nginx:
    #     image: nginx
    #     container_name: nginx-html
    #     restart: unless-stopped
    #     volumes:
    #         - ./html:/usr/share/nginx/html:ro
    #     depends_on:
    #         - microservice
    #     ports:
    #         - "8080:80"